### ISSUE TITLE
Error after install and trying to use test case

### ISSUE THREAD

**Issue by speedy32129** [sadfuzzy/redcase#3]
I get the following error:

Started GET "/redcase/index?project_id=test-redcase" for 10.2.0.68 at Thu Mar 14 16:15:53 +0000 2013
Processing by RedcaseController#index as HTML
  Parameters: {"project_id"=>"test-redcase"}
  Current user: admin (id=1)
[Redcase] Time calculation: Searching all other projects
0.0374 sec(s): Searching all other projects
  Rendered plugins/redcase/app/views/redcase/_management_execution_suites.html.erb (262.8ms)
  Rendered plugins/redcase/app/views/redcase/_management.html.erb (263.3ms)
  Rendered common/_tabs.html.erb (264.7ms)
  Rendered plugins/redcase/app/views/redcase/index.html.erb within layouts/base (271.4ms)
Completed 500 Internal Server Error in 326ms

ActionView::Template::Error (undefined method `observe_field' for #<#<Class:0xdf46098>:0xdd90a3c>):
    33:              :complete => 'full()', :html => { :id => 'list_form' } do |f| %>
    34:   <h3>
    35:     <%= l('label_execution_suite') %>: <%= f.select :id, @lists.collect { |e| [e.name, e.id] } %>
    36:     <%= observe_field :list_id, :function => 'update_exe_tree()', :with => 'list_id' %>
    37:   </h3>
    38:   <p>
    39:     <%= f.text_field :name %>
  app/views/common/_tabs.html.erb:24:in`_app_views_common__tabs_html_erb__977378593_116793270'
  app/views/common/_tabs.html.erb:23:in `each'
  app/views/common/_tabs.html.erb:23:in`_app_views_common__tabs_html_erb__977378593_116793270'
  app/helpers/application_helper.rb:263:in `render_tabs'

Also a little documentation on how it suppose to work would be good.

Hope this helps!  
Redmine 
Environment:
  Redmine version                          2.2.2.stable.11328
  Ruby version                             1.8.7 (i686-linux)
  Rails version                            3.2.11
  Environment                              production
  Database adapter                         MySQL
Redmine plugins:
  redcase                                  1.0 alpha 1.8

If you need more info let me know.

**Comment by sadfuzzy** [comment]
Hi! Have you tried to add 'prototype-rails' gem to your Gemfile?

**Comment by speedy32129** [comment]
ok I got by that error and have a new one.  Checked and found to fix the previous error I needed to add the following to the gemfile

gem 'prototype_legacy_helper', '0.0.0', :git => 'git://github.com/rails/prototype_legacy_helper.git'

before 
gem 'prototype-rails'

new error is

Started GET "/redcase/index?project_id=test-redcase" for 10.2.0.68 at Thu Mar 14 19:28:21 +0000 2013
Processing by RedcaseController#index as HTML
  Parameters: {"project_id"=>"test-redcase"}
  Current user: admin (id=1)
[Redcase] Time calculation: Searching all other projects
0.1791 sec(s): Searching all other projects
  Rendered plugins/redcase/app/views/redcase/_management_execution_suites.html.erb (6.3ms)
  Rendered plugins/redcase/app/views/redcase/_management_environments.html.erb (4.4ms)
  Rendered plugins/redcase/app/views/redcase/_management.html.erb (13.4ms)
  Rendered plugins/redcase/app/views/redcase/_execution.html.erb (1.6ms)
  Rendered common/_tabs.html.erb (33.9ms)
  Rendered plugins/redcase/app/views/redcase/index.html.erb within layouts/base (47.2ms)
Completed 500 Internal Server Error in 606ms

ActionView::Template::Error (compile error
/var/www/redmine/plugins/redcase/app/views/redcase/_execution.html.erb:31: syntax error, unexpected '.', expecting ')'
...                             .collect { |res| res.name }) );...
                              ^
/var/www/redmine/plugins/redcase/app/views/redcase/_execution.html.erb:31: syntax error, unexpected ')', expecting kEND
....collect { |res| res.name }) );@output_buffer.safe_concat('
                              ^):
    28:         <br/>
    29:         <%= l('label_result') %>:
    30:         <%= select_tag 'results', options_for_select(ExecutionResult.all(:order => 'order_num asc')
    31:                                                      .collect { |res| res.name }) %>
    32:         &nbsp;
    33:         <%= submit_tag l(:label_button_save), :onclick => 'execute()' %>
    34:         <br/>
  app/views/common/_tabs.html.erb:24:in `_app_views_common__tabs_html_erb__408080877_106078460'
  app/views/common/_tabs.html.erb:23:in`each'
  app/views/common/_tabs.html.erb:23:in `_app_views_common__tabs_html_erb__408080877_106078460'
  app/helpers/application_helper.rb:263:in`render_tabs'

**Comment by sadfuzzy** [comment]
Closed with SHA: 969b81956cadaf39bf67c71d6b86d3c068fe7da6
