### ISSUE TITLE
не правильно формируется ссылка в разделе Test Cases - Management - Test suites

### ISSUE THREAD

**Issue by osterik** [sadfuzzy/redcase#5]
когда разворачиваешь дерево списка тестов, при выборе теста из списка
1) ничего не происходит по клику правой кнопкой мыши (а может это фича?)

2)при вызове контекстного меню пункта View формируется ссылка вида
http://redmine.local/redcase/issues/10622

а правильная ссылка:
http://redmine.local/issues/10622

3) при выборе в этом же контекстном меню пункта Delete удалились все тест кейсы :(
в базе они остались в таблице issues, но в веб-интерфейсе в списке не отображаются - как вернуть?

**Comment by sadfuzzy** [comment]
1) - fixed
2) - fixed
