### ISSUE TITLE
get some error

### ISSUE THREAD

**Issue by kay54068** [sadfuzzy/redcase#7]
I get some error:

Completed 200 OK in 2479ms (Views: 1566.1ms | ActiveRecord: 84.0ms)
Started GET "/redcase/index?project_id=a5" for 127.0.0.1 at 2013-03-16 01:35:40
+0800
Processing by RedcaseController#index as HTML
  Parameters: {"project_id"=>"a5"}
  Current user: admin (id=1)
  Rendered plugins/redcase/app/views/redcase/_management_execution_suites.html.e
rb (263.0ms)
  Rendered plugins/redcase/app/views/redcase/_management.html.erb (264.0ms)
  Rendered common/_tabs.html.erb (267.0ms)
  Rendered plugins/redcase/app/views/redcase/index.html.erb within layouts/base
(295.0ms)
Completed 500 Internal Server Error in 427ms

ActionView::Template::Error (undefined method `remote_function' for #<#<Class:0x
7314d98>:0x720bbc8>):
    4:     <%= remote_function :url => { :action => 'update_exelists2',
    5:     :project_id => @project.id },
    6:     :update => 'execution_settings_id',
    7:     :complete => 'update_exe2_tree()' %>
    8:   }
    9:
    10:   full = function () {
  app/views/common/_tabs.html.erb:24:in`block in _app_views_common__tabs_html_e
rb__997048154_59138844'
  app/views/common/_tabs.html.erb:23:in `each'
  app/views/common/_tabs.html.erb:23:in`_app_views_common__tabs_html_erb__99704
8154_59138844'
  app/helpers/application_helper.rb:263:in `render_tabs'

**Comment by sadfuzzy** [comment]
Please, update the plugin and run "bundle install"!
