### ISSUE TITLE
Unable to install in Redmine 2.2.4.stable.11577

### ISSUE THREAD

**Issue by Assar63** [sadfuzzy/redcase#8]
Hi!
Just tried to install it in Redmine 2.2.4.stable.11577
This is the environment:
Environment:
  Redmine version                          2.2.4.stable.11577
  Ruby version                             1.9.3 (x86_64-linux)
  Rails version                            3.2.13
  Environment                              production
  Database adapter                         Mysql2
Redmine plugins:
  redmine_backlogs                         v0.9.37
  redmine_dmsf                             1.4.5 stable
  redmine_knowledgebase                    2.2.0
  redmine_wiki_extensions                  0.6.2

I get this problem 
/var/lib/gems/1.9.1/gems/activerecord-3.2.13/lib/active_record/connection_adapters/abstract/connection_specification.rb:47:in `resolve_hash_connection': database configuration does not specify adapter (ActiveRecord::AdapterNotSpecified)
    from /var/lib/gems/1.9.1/gems/activerecord-3.2.13/lib/active_record/connection_adapters/abstract/connection_specification.rb:41:in`resolve_string_connection'
    from /var/lib/gems/1.9.1/gems/activerecord-3.2.13/lib/active_record/connection_adapters/abstract/connection_specification.rb:25:in `spec'
    from /var/lib/gems/1.9.1/gems/activerecord-3.2.13/lib/active_record/connection_adapters/abstract/connection_specification.rb:130:in`establish_connection'
    from /var/lib/gems/1.9.1/gems/activerecord-3.2.13/lib/active_record/railtie.rb:82:in `block (2 levels) in <class:Railtie>'
    from /var/lib/gems/1.9.1/gems/activesupport-3.2.13/lib/active_support/lazy_load_hooks.rb:36:in`instance_eval'
    from /var/lib/gems/1.9.1/gems/activesupport-3.2.13/lib/active_support/lazy_load_hooks.rb:36:in `execute_hook'
    from /var/lib/gems/1.9.1/gems/activesupport-3.2.13/lib/active_support/lazy_load_hooks.rb:26:in`block in on_load'
    from /var/lib/gems/1.9.1/gems/activesupport-3.2.13/lib/active_support/lazy_load_hooks.rb:25:in `each'
    from /var/lib/gems/1.9.1/gems/activesupport-3.2.13/lib/active_support/lazy_load_hooks.rb:25:in`on_load'
    from /var/lib/gems/1.9.1/gems/activerecord-3.2.13/lib/active_record/railtie.rb:74:in `block in <class:Railtie>'
    from /var/lib/gems/1.9.1/gems/railties-3.2.13/lib/rails/initializable.rb:30:in`instance_exec'
    from /var/lib/gems/1.9.1/gems/railties-3.2.13/lib/rails/initializable.rb:30:in `run'
    from /var/lib/gems/1.9.1/gems/railties-3.2.13/lib/rails/initializable.rb:55:in`block in run_initializers'
    from /var/lib/gems/1.9.1/gems/railties-3.2.13/lib/rails/initializable.rb:54:in `each'
    from /var/lib/gems/1.9.1/gems/railties-3.2.13/lib/rails/initializable.rb:54:in`run_initializers'
    from /var/lib/gems/1.9.1/gems/railties-3.2.13/lib/rails/application.rb:136:in `initialize!'
    from /var/lib/gems/1.9.1/gems/railties-3.2.13/lib/rails/railtie/configurable.rb:30:in`method_missing'
    from /var/www/redmine-2.2/config/environment.rb:14:in `<top (required)>'
    from /var/lib/gems/1.9.1/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:251:in`require'
    from /var/lib/gems/1.9.1/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:251:in `block in require'
    from /var/lib/gems/1.9.1/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:236:in`load_dependency'
    from /var/lib/gems/1.9.1/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:251:in `require'
    from /var/lib/gems/1.9.1/gems/railties-3.2.13/lib/rails/application.rb:103:in`require_environment!'
    from /var/lib/gems/1.9.1/gems/railties-3.2.13/lib/rails/commands.rb:25:in `<top (required)>'
    from script/rails:6:in`require'
    from script/rails:6:in `<main>'

**Comment by sadfuzzy** [comment]
Please, specify your connection adapter (mysql2/postgresql/sqlite) in 'config' directory, 'database.yml' file.

**Comment by Assar63** [comment]
production:
  adapter: mysql2
  database: redmine
  host: localhost
  port: 
  username: *********
  password: **********
  encoding: utf8

**Comment by sadfuzzy** [comment]
Hmm, try:

```
gem install bundler
bundle install --without development test
bundle exec rake generate_secret_token
bundle exec rake db:create
RAILS_ENV=production bundle exec rake db:migrate
```

**Comment by Assar63** [comment]
Thanks.
Will try this next week.
As I run this in debian, I need to keep close track on gems.
New migrate command is
rake redmine:plugins:migrate RAILS_ENV=production

**Comment by felixonmars** [comment]
Hi, I'm installing redcase on Redmine 2.3.3.stable (latest), and getting the same error as Assar63.

After the given "new" migrate command, the migration process seems to work (no error), but after added a test case, the test case tab will raise a 500 error:

```
NoMethodError (undefined method `strip_tags' for #<RedcaseController:0x00000007bebdb8>):
  app/helpers/application_helper.rb:821:in `block in parse_headings'
  app/helpers/application_helper.rb:819:in `gsub!'
  app/helpers/application_helper.rb:819:in `parse_headings'
  app/helpers/application_helper.rb:516:in `textilizable'
```

I'm not sure if it's of a similar problem, but really appreciate if anyone can help!

**Comment by felixonmars** [comment]
Oops I've "fixed" mine, seems not related to this one though.

I'm new to Ruby, this is just a quick hack:

change app/helpers/application_helper.rb line 822
from

```
      item = strip_tags(content).strip
```

to

```
      item = ActionController::Base.helpers.strip_tags(content).strip
```

Hope this helps someone

**Comment by Assar63** [comment]
Old issue!
